Description: >
    This template is design to deploy EC2 instance in AWS environment.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VpcID:
    Description: VPC ID for Resources
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: VpcID
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: KeyName
    Type: AWS::SSM::Parameter::Value<AWS::EC2::KeyPair::KeyName>
    ConstraintDescription: must be the name of an existing EC2 KeyPair
  InstanceType:
    Description : App EC2 instance type
    Type: AWS::SSM::Parameter::Value<String>
    Default: InstanceType
  SubnetID:
    Description: Subnet Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: SubnetID
  ImageID:
    Description: App EC2 image Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: ImageID
Resources:
   EC2Instance1:
     Type: AWS::EC2::Instance
     Properties:
       InstanceType: !Ref InstanceType
       KeyName: !Ref KeyName
       DisableApiTermination: true
       ImageId: !Ref ImageID
       SubnetId: !Ref SubnetID
       SecurityGroupIds:
         - !Ref  InstanceSecurityGroup
       BlockDeviceMappings:
         - DeviceName: /dev/sda1
           Ebs:
              VolumeSize: 80
         - DeviceName: /dev/xvdf
           Ebs:
              VolumeSize: 80     
       Tags:
         - Key: Name
           Value: !Sub "${EnvironmentName}-test01"
         - Key: Product
           Value: test
         - Key: Type
           Value: AppServer
       UserData:
          'Fn::Base64': !Sub  |
              #!/bin/bash
              apt-get update
              apt-get install nginx -y
              systemctl enable nginx              
              systemctl start nginx

              # Create a sample index.html file
              echo "<html>
              <head>
                <title>Welcome to Nginx on AWS</title>
              </head>  
              <body>
                <h1>SAMPLE WEBPAGE Using CloudFormation</h1>
                <p>This is a sample webpage served by Nginx on an AWS EC2 instance.</p>
              </body>
              </html>" > /var/www/html/index.html  

   InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP access"
      VpcID: !Ref VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allows HTTP access from anywhere (use with caution)              
